### ISSUE TITLE
[FEATURE] Small offroad vehicle

### ISSUE THREAD

**Issue by Polystation22b** [boot2big/immersive_vehicles_vanity#1]
something small and capable off and on road
![image](https://user-images.githubusercontent.com/55518706/186329309-31df2623-d20f-4102-bbe5-85ce0c06b268.png)

**Comment by boot2big** [comment]
Likely not a jeep, but will consider something like this

**Comment by boot2big** [comment]
![image](https://user-images.githubusercontent.com/53581325/186830077-3e193e0a-11d9-4213-86c7-8c45df070111.png)

Still needs a vehicle, wheel and engine json, but progress is being made

**Comment by boot2big** [comment]
Implemented before b7fd25e4c06230a6c6ff67ba701bc226878d0070 but I just discovered this is a thing and I'm going to use it here too, since this should've been closed
