### ISSUE TITLE
(Bug) Guns still appearing when i unequip them

### ISSUE THREAD

**Issue by Arockk12** [boot2big/immersive_vehicles_vanity#15]
I tried to equip a gun and fire it but when i unequip it the view model doesnt go away. I dont know much about coding so im just leaving it here.

**Comment by boot2big** [comment]
I've not yet encountered an issue like this myself, but I'll keep it in mind during bugtesting. Thanks!

**Comment by boot2big** [comment]
@Arockk12 Which version of IVV and MTS were you using at the time?

**Comment by boot2big** [comment]
Closed after one week of inactivity without any additional information
