### ISSUE TITLE
IVV Helix pickup isn't able to tow other pack's trailers

### ISSUE THREAD

**Issue by IronSasquatch33** [boot2big/immersive_vehicles_vanity#16]
First of all I love your pack, don't give up on it.
Secondly the helix pickup is unable to tow other packs trailers.
I love the fact that you can mount guns on vehicles and control them from the driver's seat, that is something that all the packs should implement. Just remember that you have at one person who cares about your pack.

**Comment by boot2big** [comment]
I have had a couple ideas in mind to implement cross-pack compatibility for trailers, this will be fixed by release 2.2.0 :+1:

**Comment by boot2big** [comment]
P.S Helix is due for a remodel as well, which will accommodate the convention-compatible part solution!

**Comment by boot2big** [comment]
Fixed in latest 2.2.0 update
