### ISSUE TITLE
[ bug ] When downloaded, every car and the kobold go crazy

### ISSUE THREAD

**Issue by juuoo13** [boot2big/immersive_vehicles_vanity#18]
just got this mod

 it does a weird burnout and massive car revving

https://user-images.githubusercontent.com/95724674/234748073-b421ecc1-d2d7-4732-aa66-331b4e6ed7d3.mp4

(no audio due to very loud speakers)

**Comment by boot2big** [comment]
From what I can see in this video, it appears to be caused by the core mod's default simpleThrottle behavior.

Can you try disabling simpleThrottle in the MTS configuration tab to see if this still occurs?

**Comment by juuoo13** [comment]
yep it worked thanks
