### ISSUE TITLE
Engine Tuning Bench Problem

### ISSUE THREAD

**Issue by PawelW2006** [boot2big/immersive_vehicles_vanity#19]
When i place the I5 Performante in the Engine Tuning Bench and Install a Turbocharger on it, the engine is impossible to get out of the bench, clicking it with wrench either removes the bench or a random engine mod but not the engine itself.

This does not hapen with either FRM upgrade or Valvetrain Upgrade on the I5 Performante, only with Turbochargers.
This does not happen with Turbochargers on any other engine i tested.

**Comment by boot2big** [comment]
Sounds like I have a missing `"allowParentRemoval"` parameter for that engine, sorry for the inconvenience and thank you for reporting this!

**Comment by boot2big** [comment]
Fixed with 0afd295 commit
