### ISSUE TITLE
Glockinator handgun causes crash when in inventory

### ISSUE THREAD

**Issue by Ironsasquatch3345** [boot2big/immersive_vehicles_vanity#20]
[crash-2023-12-21_16.20.58-server.txt](https://github.com/boot2big/immersive_vehicles_vanity/files/13746004/crash-2023-12-21_16.20.58-server.txt)

**Comment by boot2big** [comment]
This issue is caused by a variable in the core mod causing a crash when it is referenced on a gun that has never been reloaded before. To fix this, use the latest beta version of Immersive Vehicles or use a previous version that does not contain `gun_ammo_reloading`

**Comment by boot2big** [comment]
Have added a patch for outdated MTS versions regardless, will be released in a hotfix soon

**Comment by boot2big** [comment]
Fixed in V2.31.0
