### ISSUE TITLE
Bicycles do not move.

### ISSUE THREAD

**Issue by NoMoreUsernames999** [boot2big/immersive_vehicles_vanity#21]
Immersive vehicles V22.13
Vanity V2.31.1 

Bicycles don't seem to work. Starting their "engine" and putting them into gear gets it moving slowly, but as soon as you apply gas it stops. Rinse and repeat. I'm wondering if this has something to do with the bikes in general, because the dirt bike things have a somewhat similar issue. If you apply full throttle, they stall. But if you tap the gas a few times to get it up to speed, then you can hold W and it works fine.

**Comment by boot2big** [comment]
Could you post a video of this behavior? I'm not sure I entirely understand the issue, or at least how it could occur based on how you've described it

**Comment by NoMoreUsernames999** [comment]
Sure, here ya go. Doesn't seem to happen with any other pack (I'm also using WARK IV farming, the official pack, and something else I can't remember the name of). With the bike, any amount of throttle stalls it. With the motorbike, holding throttle also stalls, unless you tap it a few times to get it up to speed as in the first example.
 
https://youtu.be/_cCZXEr8LrU

**Comment by NoMoreUsernames999** [comment]
Oh huh. Sorry, ignore this issue. I seem to have had an older MTS config that was messing with the mod. On a hunch deleted the configs and let them reload, and it's working now (mostly. The motorbike still stalls often, which seems to be a feature? But the bicycles work fine now. My bad lol).

**Comment by boot2big** [comment]
Huh, I will have to look into the issue with the Kobold, otherwise glad that the issue with the bicycle is resolved! :+1:

**Comment by NoMoreUsernames999** [comment]
Uhhhh, ok nvm. It seems that enabling the config option "disable auto start throttle" is what's breaking it. Uh... idk if this is intended but, should i reopen this issue or.... ? I always have that option off since it makes aircraft really annoying to control when doing pre-flight checks.
